# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23a7b3a394e51d1de1c9ee6ac601221ffb54f65835c69f2d27cf5c674f8ddf0f1bb2bba945351b775616047303d3dbe2eeaf00c94249be5531a09a5c875a3fdf

test:
  secret_key_base: 70f49235597e9f495a31d6cd20667905e47867e7ea32305c332cc9906ad59148324330e78e85a44018892d837edfd524a62eff421d6ddd24de9f16de0d64861a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
